### ISSUE TITLE
Demo API is down

### ISSUE THREAD

**Issue by xaviemirmon** [konstantinmuenster/graphql-weather-api#1]
Hi @konstantinmuenster 

Thanks for this API!

Just a quick ping to let you know I've been unable to connect to the Heroku instance since yesterday.  https://graphql-weather-api.herokuapp.com/ has been showing the following error message.

![Screenshot 2023-03-03 at 17 40 52](https://user-images.githubusercontent.com/5609840/222790613-5246cbc0-d5f3-46df-b82a-053cfa93a688.png)

**Comment by konstantinruge** [comment]
Hey @xaviemirmon! Yes, heroku removed their free tier recently. Since I don't want to pay for this demo application, I need to move it somewhere else - but haven't had the chance to do it so far.
